services:
  node:
    env_file:
      - path: .env
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
  postgres:
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
